import React from 'react'
import { View,Text, StyleSheet,ScrollView } from 'react-native';

function PrivacyPolicy() {
    return (
        <View style={styles.container}>
            <ScrollView>
            <View style={{height:20}}></View>
                <Text style={styles.heading1}>
                Privacy Policy
                </Text>
                <View style={{height:10}}></View>
                <Text>
                Last updated: March 08, 2021
                </Text>
                <View style={{height:20}}></View>
                <Text>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </Text>
                <Text>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
                </Text>
                <View style={{height:20}}></View>
                <Text style={styles.heading1}>
                Interpretation and Definitions
                </Text>
                <View style={{height:10}}></View>
                <Text style={styles.heading2}>
                  Interpretation
                </Text>
                <Text>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </Text>
                <View style={{height:10}}></View>
                <Text style={styles.heading2}>
                    Definitions
                </Text>
                <Text>
                For the purposes of this Privacy Policy:
                </Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Account</Text> means a unique account created for You to access our Service or parts of our Service.</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Affiliate</Text> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Application</Text> means the software program provided by the Company downloaded by You on any electronic device, named T4</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Company</Text> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to T4.</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Country</Text> refers to: Kerala, India</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Device</Text> means any device that can access the Service such as a computer, a cellphone or a digital tablet. </Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Personal Data</Text> is any information that relates to an identified or identifiable individual.</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Service</Text> refers to the Application. </Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Service Provider</Text> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Third-party Social Media Service</Text> refers to any website or any social network website through which a User can log in or create an account to use the Service.</Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). </Text>
                <View style={{height:10}}></View>
                <Text><Text style={styles.heading3}>You</Text> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
            
            <View style={{height:30}}></View>
            <Text style={styles.heading1}>Collecting and Using Your Personal Data</Text>
            <View style={{height:10}}></View>
            <Text style={styles.heading2}>Types of Data Collected</Text>
            <View style={{height:10}}></View>
            <Text style={styles.heading4}>Personal Data</Text>
            <View style={{height:10}}></View>
            <Text>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</Text>
            <View style={{height:10}}></View>
            <Text>* Email address </Text>
            <View style={{height:5}}></View>
            <Text>* First name and last name</Text>
            <View style={{height:5}}></View>
            <Text>* Phone number</Text>
            <View style={{height:5}}></View>
            <Text>* Address, State, Province, ZIP/Postal code, City </Text>
            <View style={{height:5}}></View>
            <Text>* Profile picture </Text>
            <View style={{height:5}}></View>
            <Text>* Usage Data</Text>
          
            <View style={{height:20}}></View>
            <Text style={styles.heading4}>Usage Data</Text>
            <View style={{height:10}}></View>
            <Text>Usage Data is collected automatically when using the Service.</Text>
            <Text>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</Text>
            <Text>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</Text>
            <Text>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</Text>
            <View style={{height:20}}></View>
            <Text style={styles.heading4}>Information Collected while Using the Application</Text>
            <View style={{height:10}}></View>
            <Text>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</Text>
            
            <Text>Information regarding your location</Text>
            <Text>Pictures and other information from your Device's camera and photo library</Text>
            <Text>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</Text>
            <Text>You can enable or disable access to this information at any time, through Your Device settings.</Text>
            <View style={{height:20}}></View>
            <Text style={styles.heading2}>Use of Your Personal Data</Text>
            <View style={{height:10}}></View>
            <Text>The Company may use Personal Data for the following purposes:</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>To provide and maintain our Service</Text>, including to monitor the usage of our Service.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>To manage Your Account:</Text> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>For the performance of a contract:</Text> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>To contact You:</Text> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>To provide You</Text> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>To manage Your requests:</Text> To attend and manage Your requests to Us.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>For business transfers: </Text>We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>For other purposes:</Text> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</Text>
            <View style={{height:10}}></View>
            <Text>We may share Your personal information in the following situations:</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>With Service Providers:</Text> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</Text>
            <View style={{height:10}}></View>
           <Text><Text style={styles.heading3}>For business transfers:</Text> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</Text>
           <View style={{height:10}}></View>
           <Text><Text style={styles.heading3}>With Affiliates: </Text>We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</Text>
           <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>With business partners:</Text>  We may share Your information with Our business partners to offer You certain products, services or promotions.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>With other users: </Text> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</Text>
            <View style={{height:10}}></View>
            <Text><Text style={styles.heading3}>With Your consent: </Text> We may disclose Your personal information for any other purpose with Your consent.</Text>
            <View style={{height:30}}></View>
            <Text style={styles.heading2}>Retention of Your Personal Data</Text>
            <View style={{height:10}}></View>
            <Text>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</Text>
            <Text>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</Text>
            <View style={{height:30}}></View>
           <Text style={styles.heading2}>Transfer of Your Personal Data</Text>
           <View style={{height:10}}></View>
           <Text>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</Text>
           <Text>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</Text>
            <Text>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</Text>
            <View style={{height:30}}></View>
        <Text style={styles.heading2}>Disclosure of Your Personal Data</Text>
        <View style={{height:20}}></View>
        <Text style={styles.heading4}>Business Transactions</Text>
        <View style={{height:10}}></View>
        <Text>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</Text>
        <View style={{height:20}}></View>
        <Text style={styles.heading4}>Law enforcement</Text>
        <View style={{height:10}}></View>
        <Text>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</Text>
        <View style={{height:20}}></View>
        <Text style={styles.heading4}>Other legal requirements</Text>
        <View style={{height:10}}></View>
        <Text>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</Text>
        <Text>Comply with a legal obligation </Text>
        <Text>Protect and defend the rights or property of the Company</Text>
        <Text>Prevent or investigate possible wrongdoing in connection with the Service</Text>
        <Text>Protect the personal safety of Users of the Service or the public</Text>
        <Text>Protect against legal liability</Text>
        <View style={{height:20}}></View>
        <Text style={styles.heading2}>Security of Your Personal Data</Text>
        <View style={{height:10}}></View>
        <Text>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</Text>
        <View style={{height:30}}></View>
        <Text style={styles.heading1}>Children's Privacy</Text>
        <View style={{height:10}}></View>
        <Text>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</Text>
        <Text>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</Text>
        <View style={{height:30}}></View>
        <Text style={styles.heading1}>Links to Other Websites</Text>
        <View style={{height:10}}></View>
        <Text>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</Text>
        <Text>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Text>
        
        <View style={{height:30}}></View>
        <Text style={styles.heading1}>Changes to this Privacy Policy</Text>
        <View style={{height:10}}></View>
        <Text>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</Text>
        <Text>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</Text>
        <Text>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</Text>
        <View style={{height:30}}></View>
       <Text style={styles.heading1}>Contact Us</Text>
       <View style={{height:10}}></View>
       <Text>If you have any questions about this Privacy Policy, You can contact us:</Text>
       <Text>By email: rashidrcp84@gmail.com</Text>
       <View style={{height:50}}></View>
        </ScrollView>
        </View>
    )
}

export default PrivacyPolicy

const styles= StyleSheet.create({
 container:{
     flex:1,
     padding:10,
 },
 heading1:{
    fontSize:25,
    fontWeight:'700',

 },
 heading2:{
     fontSize:20,
     fontWeight:'700',
 },
 heading3:{
     fontSize:15,
     fontWeight:'700',
 },
 heading4:{
     fontSize:18,
     fontWeight:'700',
 }


})